In [22]:
using ControlSystems
using Polynomials
using Plots

In [23]:
PlossT = 0.5;
n = 0.1;
Vin = 230 * sqrt(2);
Pout = 100;
Vout = 5;
fs = 2500;
k = 0.01;
Rp = 0.001;
Rs = 0.0001;
Lm = 5e-3;
Cf = 5e-3;
D0 = roots(Polynomial([Vout, Rs * Pout / Vout - n * Vin - 2 * Vout, (n^2 * Rp - Rs) * Pout / Vout + n * Vin + Vout]))[1];
Req = D0 * Rp + (1 - D0) * Rs / n^2;

In [24]:
A = [(-D0*Req/Lm) (-(1 - D0)/(n*Lm)); (1-D0)/(n*Cf) 0]

2×2 Matrix{Float64}:
   -0.234532  -1733.51
 1733.51          0.0

In [25]:
B = [0 D0/Lm (((1-D0)*Vin-n*Req*Pout/Vout)/(Lm*(1-D0)^2)); -1/Cf 0 -Pout/(Vout*Cf*(1-D0))]

2×3 Matrix{Float64}:
    0.0  26.649  75049.8
 -200.0   0.0    -4614.91

In [26]:
C = [0 1]

1×2 Matrix{Int64}:
 0  1

In [27]:
D = [0 0 0]

1×3 Matrix{Int64}:
 0  0  0

In [28]:
sys = ss(A, B, C, D)

StateSpace{Continuous, Float64}
A = 
   -0.2345322727557256  -1733.5101489152457
 1733.5101489152457         0.0
B = 
    0.0  26.648985108475415  75049.7623777771
 -200.0   0.0                -4614.913852685573
C = 
 0.0  1.0
D = 
 0.0  0.0  0.0

Continuous-time state-space model

In [31]:
t = 0:1e-7:1;
u1 = zeros(1, length(t))
u2 = 0.2 * 230 * sin.(t')
u3 = zeros(1, length(t))
u = [u1; u2; u3]
y, _ = lsim(sys, u, t)
plot(t, y' .+ Vout)

In [30]:
G = tf(sys)

TransferFunction{Continuous, ControlSystemsBase.SisoRational{Float64}}
Input 1 to output 1
           -200.0s - 46.906454551033676
---------------------------------------------------
1.0s^2 + 0.2345322727557256s + 3.0050574363921573e6

Input 2 to output 1
                 46196.28614383377
---------------------------------------------------
1.0s^2 + 0.2345322727557256s + 3.0050574363921573e6

Input 3 to output 1
    -4614.913852685573s + 1.3009844240931973e8
---------------------------------------------------
1.0s^2 + 0.2345322727557256s + 3.0050574363921573e6

Continuous-time transfer function model